version: '3.6'
services:
  refrigerator-fix:
    image: refrigerator-fix:latest
    build: .
    restart: always
    volumes:
      - ${PWD}/config.json:/root/config.json
      - ${PWD}/refrigerator-temperature-log.csv:/root/refrigerator-temperature-log.csv
