name: Docker-Publish

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: refrigerator-fix
  REGISTRY_USER: JulianSauer
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Log into registry
        run: docker login docker.pkg.github.com --username "$REGISTRY_USER" -p "$REGISTRY_PASSWORD"

      - name: Push image
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          docker tag $IMAGE_NAME $IMAGE_ID:latest
          docker tag $IMAGE_NAME $IMAGE_ID:$GITHUB_SHA
          docker push $IMAGE_ID:latest
          docker push $IMAGE_ID:$GITHUB_SHA
